/**
 * Generates `dist/catalog.json` - every measurable mockup, variant and
 * orientation, with each live region's size in world units, millimetres and
 * CSS pixels.
 *
 * The catalog is a build artifact, never hand-edited: it is `mockupInfo`
 * evaluated over the whole registry. That makes it the one place docs tables,
 * design-tool plugins and non-JS consumers can read the numbers from without
 * re-deriving them (and without going stale on the next accuracy pass).
 *
 * Run after tsup, so it can import the built core modules:
 *   node scripts/build-catalog.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath, pathToFileURL } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, '..', 'dist')

// `import()` of an absolute path only works on POSIX; on Windows `C:\...` reads
// as a `c:` URL scheme and throws. A file:// URL is portable across both.
// The enumeration and its typing live in `src/core/catalog.ts`, where the
// unit tests can read them; this script only writes the result.
const { catalogEntries } = await import(pathToFileURL(join(dist, 'core', 'catalog.js')).href)
const { MOCKUP_KINDS } = await import(pathToFileURL(join(dist, 'core', 'index.js')).href)
const entries = catalogEntries()

const catalog = {
  $comment: 'Generated by scripts/build-catalog.mjs - do not edit by hand.',
  // 2: fold, flip and iPhone Duo rows carry `openAngle` (version 1 named a
  // nonexistent `open` prop and so catalogued the open screen twice), and the
  // TV is enumerated by variant.
  version: 2,
  kinds: MOCKUP_KINDS,
  entries,
}

writeFileSync(join(dist, 'catalog.json'), JSON.stringify(catalog, null, 2) + '\n')
console.log(`catalog.json: ${entries.length} entries across ${MOCKUP_KINDS.length} kinds`)
