/**
 * Generates `dist/catalog.json` - every measurable mockup, variant and
 * orientation, with each live region's size in world units, millimetres and
 * CSS pixels.
 *
 * The catalog is a build artifact, never hand-edited: it is `mockupInfo`
 * evaluated over the whole registry. That makes it the one place docs tables,
 * design-tool plugins and non-JS consumers can read the numbers from without
 * re-deriving them (and without going stale on the next accuracy pass).
 *
 * Run after tsup, so it can import the built core bundle:
 *   node scripts/build-catalog.mjs
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const here = dirname(fileURLToPath(import.meta.url))
const dist = join(here, '..', 'dist')

const core = await import(join(dist, 'core.js'))
const { mockupInfo, MOCKUP_KINDS } = core

/**
 * Which variants and orientations to enumerate per kind. Anything absent is
 * emitted once, at its default props.
 */
const AXES = {
  galaxy: { variant: Object.keys(core.GALAXY_VARIANTS), orientation: ['portrait', 'landscape'] },
  iphone: { variant: Object.keys(core.IPHONE_VARIANTS), orientation: ['portrait', 'landscape'] },
  laptop: { variant: Object.keys(core.LAPTOP_VARIANTS) },
  ipad: { variant: Object.keys(core.IPAD_VARIANTS), orientation: ['portrait', 'landscape'] },
  galaxyTab: { variant: Object.keys(core.GALAXY_TAB_VARIANTS), orientation: ['portrait', 'landscape'] },
  appleWatch: { variant: Object.keys(core.APPLE_WATCH_VARIANTS) },
  galaxyWatch: { variant: Object.keys(core.GALAXY_WATCH_VARIANTS) },
  fold: { variant: Object.keys(core.FOLD_VARIANTS), open: [true, false], orientation: ['portrait', 'landscape'] },
  flip: { variant: Object.keys(core.FLIP_VARIANTS), open: [true, false], orientation: ['portrait', 'landscape'] },
  posterFrame: { mat: [false, true] },
  // `perforated` shares `full`'s rects, so enumerating it would duplicate rows.
  bus: { coverage: ['panel', 'full'] },
  van: { coverage: ['panel', 'full'] },
}

/** The two kinds whose `size` prop is required have no meaningful default. */
const REQUIRED_PROPS = {
  customPanel: { size: { width: 100, height: 150 } },
  customBox: { size: { width: 250, height: 90, depth: 160 } },
}

/** Cartesian product of an axis spec, always yielding at least `{}`. */
function combinations(axes) {
  let out = [{}]
  for (const [key, values] of Object.entries(axes ?? {})) {
    out = out.flatMap((base) => values.map((value) => ({ ...base, [key]: value })))
  }
  return out
}

const entries = []
for (const kind of MOCKUP_KINDS) {
  for (const combo of combinations(AXES[kind])) {
    const props = { ...REQUIRED_PROPS[kind], ...combo }
    const info = mockupInfo(kind, props)
    entries.push({
      kind,
      props,
      mmPerUnit: info.mmPerUnit,
      primary: info.primary.name,
      regions: info.list.map((r) => ({
        name: r.name,
        label: r.label,
        index: r.index,
        units: r.units,
        mm: r.mm,
        px: r.px,
        resolution: r.resolution,
        aspect: r.aspect,
      })),
    })
  }
}

const catalog = {
  $comment: 'Generated by scripts/build-catalog.mjs - do not edit by hand.',
  version: 1,
  kinds: MOCKUP_KINDS,
  entries,
}

writeFileSync(join(dist, 'catalog.json'), JSON.stringify(catalog, null, 2) + '\n')
console.log(`catalog.json: ${entries.length} entries across ${MOCKUP_KINDS.length} kinds`)
